package com.jisuanyusuiji.toolbox.tools.vocab

data class VocabWord(
    val word: String,
    val phonetic: String,
    val meanings: String,
    val usage: String = "",
    val phrases: String = "",
    val pastTense: String = "",
    val pastParticiple: String = "",
    val example: String = "",
    val derivatives: String = "",
    val synonyms: String = "",
    val antonyms: String = "",
    val similar: String = ""
)

/** 内置高频词精讲（可自行导入更多词库）。 */
object VocabData {
    val builtIn: List<VocabWord> = listOf(
        VocabWord("abandon", "/əˈbændən/", "v. 放弃；抛弃；离弃；停止", "abandon doing sth 放弃做某事", "abandon oneself to 沉溺于", "abandoned", "abandoned", "He abandoned his plan to study abroad.", "abandonment n. 放弃", "desert, quit", "keep, retain", "abundant adj. 丰富的"),
        VocabWord("abstract", "/ˈæbstrækt/", "adj. 抽象的；n. 摘要；v. 提取", "abstract concept 抽象概念", "in the abstract 抽象地", "", "", "Beauty is an abstract idea.", "abstraction n. 抽象", "theoretical", "concrete", "attract v. 吸引"),
        VocabWord("academic", "/ˌækəˈdemɪk/", "adj. 学术的；学业的；n. 学者", "academic performance 学业成绩", "academic year 学年", "", "", "She has an excellent academic record.", "academy n. 学院", "scholarly", "practical", "epidemic n. 流行病"),
        VocabWord("accommodate", "/əˈkɒmədeɪt/", "v. 容纳；为…提供住宿；适应；迁就", "accommodate to 适应", "accommodate sb with sth 向某人提供某物", "accommodated", "accommodated", "The hotel can accommodate 500 guests.", "accommodation n. 住宿", "hold, adapt", "reject", "accumulate v. 积累"),
        VocabWord("accomplish", "/əˈkʌmplɪʃ/", "v. 完成；实现；达到", "accomplish a task 完成任务", "accomplish one's goal 实现目标", "accomplished", "accomplished", "We accomplished the project on time.", "accomplishment n. 成就", "achieve, complete", "fail", "complete v. 完成"),
        VocabWord("accumulate", "/əˈkjuːmjəleɪt/", "v. 积累；积聚；堆积", "accumulate wealth 积累财富", "accumulate experience 积累经验", "accumulated", "accumulated", "Dust had accumulated on the shelves.", "accumulation n. 积累", "gather, amass", "disperse", "accommodate v. 容纳"),
        VocabWord("acknowledge", "/əkˈnɒlɪdʒ/", "v. 承认；确认收到；致谢；意识到", "acknowledge doing sth 承认做过某事", "be acknowledged as 被公认为", "acknowledged", "acknowledged", "He acknowledged his mistake.", "acknowledgement n. 承认", "admit, recognize", "deny", "knowledge n. 知识"),
        VocabWord("acquire", "/əˈkwaɪə(r)/", "v. 获得；取得；学到；购得", "acquire knowledge 学习知识", "acquire a taste for 喜欢上", "acquired", "acquired", "She acquired a good command of English.", "acquisition n. 获得", "obtain, gain", "lose", "require v. 需要"),
        VocabWord("adapt", "/əˈdæpt/", "v. 适应；改编；改造", "adapt to 适应", "be adapted from 由…改编", "adapted", "adapted", "Children adapt to new environments quickly.", "adaptation n. 适应；改编", "adjust, modify", "resist", "adopt v. 采纳"),
        VocabWord("adequate", "/ˈædɪkwət/", "adj. 足够的；适当的；胜任的", "adequate for 足以…", "be adequate to do 足以做", "", "", "The food supply is adequate for everyone.", "adequacy n. 充足", "sufficient, enough", "inadequate", "accurate adj. 准确的"),
        VocabWord("advocate", "/ˈædvəkeɪt/", "v. 提倡；拥护；n. 拥护者；律师", "advocate doing sth 提倡做某事", "an advocate of …的拥护者", "advocated", "advocated", "Many experts advocate a healthy lifestyle.", "advocacy n. 拥护", "support, promote", "oppose", "avocado n. 牛油果"),
        VocabWord("affect", "/əˈfekt/", "v. 影响；感动；侵袭", "be affected by 受…影响", "affect sth/sb 影响", "affected", "affected", "Smoking seriously affects health.", "affection n. 喜爱", "influence, impact", "remain neutral", "effect n. 效果"),
        VocabWord("alleviate", "/əˈliːvieɪt/", "v. 减轻；缓解（痛苦、问题）", "alleviate pain 减轻疼痛", "alleviate pressure 缓解压力", "alleviated", "alleviated", "The medicine helped alleviate the pain.", "alleviation n. 缓解", "relieve, ease", "aggravate", "elevate v. 提升"),
        VocabWord("allocate", "/ˈæləkeɪt/", "v. 分配；拨给；分派", "allocate sth to sb 把某物分给某人", "allocate resources 分配资源", "allocated", "allocated", "The funds were allocated to education.", "allocation n. 分配", "distribute, assign", "withhold", "locate v. 定位"),
        VocabWord("ambiguous", "/æmˈbɪɡjuəs/", "adj. 模棱两可的；含糊不清的", "an ambiguous answer 含糊的回答", "be ambiguous about 对…含糊", "", "", "His reply was deliberately ambiguous.", "ambiguity n. 歧义", "vague, unclear", "explicit, clear", "ambitious adj. 有雄心的"),
        VocabWord("anticipate", "/ænˈtɪsɪpeɪt/", "v. 预期；预料；期望；预先处理", "anticipate doing sth 期待做某事", "as anticipated 正如预料", "anticipated", "anticipated", "We anticipate a rise in prices.", "anticipation n. 预期", "expect, foresee", "be surprised", "participate v. 参加"),
        VocabWord("apparent", "/əˈpærənt/", "adj. 明显的；表面上的；显而易见的", "it is apparent that… 很明显…", "for no apparent reason 没有明显原因", "", "", "It became apparent that he was lying.", "apparently adv. 显然", "obvious, evident", "hidden", "parent n. 父母"),
        VocabWord("appeal", "/əˈpiːl/", "v./n. 呼吁；吸引；上诉；恳求", "appeal to 对…有吸引力；呼吁", "appeal for help 请求帮助", "appealed", "appealed", "The design appeals to young people.", "appealing adj. 有吸引力的", "attract, plead", "repel", "appear v. 出现"),
        VocabWord("appreciate", "/əˈpriːʃieɪt/", "v. 感激；欣赏；理解；意识到；增值", "appreciate doing sth 感谢做某事", "I would appreciate it if… 如果…我将感激", "appreciated", "appreciated", "I really appreciate your help.", "appreciation n. 感激", "value, thank", "depreciate", "appropriate adj. 合适的"),
        VocabWord("appropriate", "/əˈprəʊpriət/", "adj. 合适的；恰当的；v. 挪用；占用", "appropriate for/to 适合于", "appropriate measures 恰当的措施", "appropriated", "appropriated", "Wear appropriate clothes for the interview.", "appropriately adv. 恰当地", "suitable, proper", "inappropriate", "appreciate v. 感激"),
        VocabWord("arbitrary", "/ˈɑːbɪtrəri/", "adj. 任意的；武断的；专横的", "arbitrary decision 武断的决定", "an arbitrary choice 随意的选择", "", "", "The choice of colour was quite arbitrary.", "arbitrarily adv. 任意地", "random, capricious", "reasonable", "artery n. 动脉"),
        VocabWord("assess", "/əˈses/", "v. 评估；评定；估价；对…征税", "assess the situation 评估形势", "assess the value 估价", "assessed", "assessed", "Teachers assess students' progress.", "assessment n. 评估", "evaluate, estimate", "ignore", "access n. 进入"),
        VocabWord("assume", "/əˈsjuːm/", "v. 假定；认为；承担；呈现", "assume responsibility 承担责任", "let us assume that… 假设…", "assumed", "assumed", "I assumed that he was coming.", "assumption n. 假设", "suppose, presume", "prove", "consume v. 消耗"),
        VocabWord("attribute", "/əˈtrɪbjuːt/", "v. 把…归因于；n. 属性；特质", "attribute A to B 把 A 归因于 B", "a key attribute 关键特质", "attributed", "attributed", "He attributes his success to hard work.", "attribution n. 归因", "ascribe, credit", "", "contribute v. 贡献"),
        VocabWord("authentic", "/ɔːˈθentɪk/", "adj. 真正的；真品的；可信的", "authentic Chinese food 正宗中餐", "an authentic signature 真实签名", "", "", "This is an authentic Ming vase.", "authenticity n. 真实性", "genuine, real", "fake, artificial", "author n. 作者"),
        VocabWord("bias", "/ˈbaɪəs/", "n./v. 偏见；偏向；使有偏见", "bias against 对…有偏见", "gender bias 性别偏见", "biased", "biased", "The report shows a clear bias.", "biased adj. 有偏见的", "prejudice", "fairness", "basis n. 基础"),
        VocabWord("capable", "/ˈkeɪpəbl/", "adj. 有能力的；能干的；能够的", "be capable of doing 有能力做", "a capable manager 能干的经理", "", "", "She is capable of solving the problem.", "capability n. 能力", "able, competent", "incapable", "capacity n. 容量"),
        VocabWord("capacity", "/kəˈpæsəti/", "n. 容量；能力；身份；职位", "at full capacity 满负荷", "the capacity to do 做…的能力", "", "", "The stadium has a capacity of 80,000.", "capacious adj. 宽敞的", "ability, volume", "", "capable adj. 有能力的"),
        VocabWord("cease", "/siːs/", "v. 停止；终止；结束", "cease to do 停止做", "cease fire 停火", "ceased", "ceased", "The company ceased production last year.", "ceaseless adj. 不断的", "stop, halt", "continue", "seize v. 抓住"),
        VocabWord("chronic", "/ˈkrɒnɪk/", "adj. 慢性的；长期的；积习难改的", "chronic disease 慢性病", "chronic shortage 长期短缺", "", "", "He suffers from chronic back pain.", "chronically adv. 长期地", "persistent", "acute, temporary", "chronological adj. 按时间顺序的"),
        VocabWord("cite", "/saɪt/", "v. 引用；引证；传唤；举例", "cite an example 举例", "cite sb as 引用某人作为", "cited", "cited", "She cited several studies to support her view.", "citation n. 引用", "quote, mention", "", "site n. 地点"),
        VocabWord("collapse", "/kəˈlæps/", "v./n. 倒塌；崩溃；晕倒；暴跌", "collapse under pressure 崩溃", "economic collapse 经济崩溃", "collapsed", "collapsed", "The bridge collapsed suddenly.", "", "fall, break down", "stand, recover", "collide v. 碰撞"),
        VocabWord("compensate", "/ˈkɒmpenseɪt/", "v. 补偿；赔偿；弥补；抵消", "compensate for 弥补", "compensate sb for sth 赔偿某人", "compensated", "compensated", "Nothing can compensate for the loss.", "compensation n. 补偿", "make up for", "", "complete v. 完成"),
        VocabWord("comprehensive", "/ˌkɒmprɪˈhensɪv/", "adj. 全面的；综合的；广泛的", "comprehensive analysis 全面分析", "comprehensive insurance 综合保险", "", "", "The report gives a comprehensive overview.", "comprehensively adv. 全面地", "thorough, complete", "partial", "comprehensible adj. 可理解的"),
        VocabWord("comprise", "/kəmˈpraɪz/", "v. 包含；由…组成；构成", "be comprised of 由…组成", "comprise 50% 占 50%", "comprised", "comprised", "The committee comprises ten members.", "comprisal n. 包含", "consist of, include", "exclude", "compromise n. 妥协"),
        VocabWord("concede", "/kənˈsiːd/", "v. 承认；让步；退让；给予", "concede defeat 认输", "concede that… 承认…", "conceded", "conceded", "He finally conceded that he was wrong.", "concession n. 让步", "admit, yield", "deny", "conceive v. 构想"),
        VocabWord("conceive", "/kənˈsiːv/", "v. 构想；设想；怀孕；理解", "conceive of 想象", "conceive a plan 构思计划", "conceived", "conceived", "I can't conceive of living without music.", "conceivable adj. 可想象的", "imagine, devise", "", "concede v. 承认"),
        VocabWord("confine", "/kənˈfaɪn/", "v. 限制；限定；监禁；n. 范围", "confine to 局限于", "be confined to bed 卧床", "confined", "confined", "Please confine your remarks to the topic.", "confinement n. 限制", "restrict, limit", "release", "confirm v. 确认"),
        VocabWord("conform", "/kənˈfɔːm/", "v. 遵守；符合；顺应；使一致", "conform to 遵守；符合", "conform with 与…一致", "conformed", "conformed", "All products must conform to safety standards.", "conformity n. 一致", "comply, obey", "rebel", "confirm v. 确认"),
        VocabWord("consent", "/kənˈsent/", "n./v. 同意；允许；赞成", "consent to 同意", "with one's consent 经某人同意", "consented", "consented", "She gave her consent to the marriage.", "", "agree, approve", "refuse", "content adj. 满足的"),
        VocabWord("constitute", "/ˈkɒnstɪtjuːt/", "v. 构成；组成；设立；任命", "constitute a threat 构成威胁", "be constituted of 由…组成", "constituted", "constituted", "Women constitute half of the workforce.", "constitution n. 宪法；构成", "form, make up", "dissolve", "institute n. 机构"),
        VocabWord("constrain", "/kənˈstreɪn/", "v. 限制；约束；强迫", "be constrained by 受…限制", "constrain sb to do 强迫某人做", "constrained", "constrained", "Budget cuts constrained our plans.", "constraint n. 限制", "restrict, compel", "free", "contain v. 包含"),
        VocabWord("contemplate", "/ˈkɒntəmpleɪt/", "v. 思考；考虑；凝视；打算", "contemplate doing 考虑做", "contemplate the future 思考未来", "contemplated", "contemplated", "He is contemplating changing jobs.", "contemplation n. 沉思", "consider, ponder", "ignore", "contemporary adj. 当代的"),
        VocabWord("contemporary", "/kənˈtemprəri/", "adj. 当代的；同时代的；n. 同龄人", "contemporary art 当代艺术", "be contemporary with 与…同时代", "", "", "The museum displays contemporary art.", "", "modern, current", "ancient", "temporary adj. 暂时的"),
        VocabWord("contradict", "/ˌkɒntrəˈdɪkt/", "v. 反驳；否认；与…矛盾", "contradict oneself 自相矛盾", "contradict a statement 反驳陈述", "contradicted", "contradicted", "His actions contradict his words.", "contradiction n. 矛盾", "deny, oppose", "agree, confirm", "predict v. 预测"),
        VocabWord("contribute", "/kənˈtrɪbjuːt/", "v. 贡献；捐助；投稿；促成", "contribute to 有助于；捐献给", "contribute an article 投稿", "contributed", "contributed", "Exercise contributes to good health.", "contribution n. 贡献", "donate, add", "take away", "attribute v. 归因于"),
        VocabWord("convey", "/kənˈveɪ/", "v. 传达；表达；运输；转让", "convey one's feelings 表达感情", "convey goods 运输货物", "conveyed", "conveyed", "Words cannot convey how I feel.", "conveyance n. 运输", "express, transport", "", "convoy n. 护送"),
        VocabWord("crucial", "/ˈkruːʃl/", "adj. 至关重要的；决定性的", "be crucial to/for 对…至关重要", "play a crucial role 起关键作用", "", "", "Sleep is crucial to good health.", "crucially adv. 关键地", "vital, essential", "minor", "cruel adj. 残酷的"),
        VocabWord("cultivate", "/ˈkʌltɪveɪt/", "v. 培养；陶冶；耕作；结交", "cultivate a habit 培养习惯", "cultivate land 耕地", "cultivated", "cultivated", "Reading cultivates the mind.", "cultivation n. 培养", "develop, nurture", "neglect", "culture n. 文化"),
        VocabWord("declare", "/dɪˈkleə(r)/", "v. 宣布；声明；申报；宣判", "declare war on 向…宣战", "declare that… 宣布…", "declared", "declared", "The government declared a state of emergency.", "declaration n. 宣言", "announce, state", "conceal", "decline v. 下降"),
        VocabWord("dedicate", "/ˈdedɪkeɪt/", "v. 致力于；献身；题献", "be dedicated to 致力于", "dedicate oneself to 献身于", "dedicated", "dedicated", "She dedicated her life to science.", "dedication n. 奉献", "devote, commit", "", "indicate v. 表明"),
        VocabWord("deduce", "/dɪˈdjuːs/", "v. 推断；演绎；推论", "deduce from 从…推断", "deduce that… 推断出…", "deduced", "deduced", "From the evidence we can deduce his guilt.", "deduction n. 推论", "infer, conclude", "", "reduce v. 减少"),
        VocabWord("deficiency", "/dɪˈfɪʃnsi/", "n. 缺乏；不足；缺陷；营养缺乏", "vitamin deficiency 维生素缺乏", "deficiency in 在…方面不足", "", "", "The disease is caused by a vitamin deficiency.", "deficient adj. 不足的", "shortage, lack", "sufficiency", "efficiency n. 效率"),
        VocabWord("deliberate", "/dɪˈlɪbərət/", "adj. 故意的；从容的；v. 仔细考虑", "a deliberate act 故意行为", "deliberate on 仔细考虑", "deliberated", "deliberated", "It was a deliberate attempt to mislead us.", "deliberately adv. 故意地", "intentional, consider", "accidental", "liberate v. 解放"),
        VocabWord("demonstrate", "/ˈdemənstreɪt/", "v. 证明；演示；示范；游行", "demonstrate that… 证明…", "demonstrate against 游行反对", "demonstrated", "demonstrated", "The experiment demonstrates the theory.", "demonstration n. 演示；游行", "show, prove", "conceal", "remonstrate v. 抗议"),
        VocabWord("denote", "/dɪˈnəʊt/", "v. 表示；指示；意味着", "denote a change 表示变化", "X denotes the unknown X 表示未知数", "denoted", "denoted", "The red light denotes danger.", "denotation n. 含义", "indicate, signify", "", "donate v. 捐赠"),
        VocabWord("deteriorate", "/dɪˈtɪəriəreɪt/", "v. 恶化；变坏；退化", "deteriorate rapidly 迅速恶化", "relations deteriorate 关系恶化", "deteriorated", "deteriorated", "His health deteriorated after the operation.", "deterioration n. 恶化", "worsen, decline", "improve", "determine v. 决定"),
        VocabWord("deviate", "/ˈdiːvieɪt/", "v. 偏离；背离；违背", "deviate from 偏离", "deviate from the plan 偏离计划", "deviated", "deviated", "The plane deviated from its course.", "deviation n. 偏差", "diverge, stray", "conform", "dedicate v. 奉献"),
        VocabWord("diminish", "/dɪˈmɪnɪʃ/", "v. 减少；缩小；贬低", "diminish in value 贬值", "diminishing returns 收益递减", "diminished", "diminished", "His influence has diminished over time.", "diminution n. 减少", "reduce, decrease", "increase", "finish v. 完成")
    )
}
