package com.jisuanyusuiji.toolbox.tools.knowledge

data class CarLogo(
    val name: String,
    val badge: String,
    val country: String,
    val kind: String
)

/**
 * 车标图鉴数据：只提供名称/文字徽标。
 * 真实车标图片受版权保护，可由用户自行导入并保存在本机。
 * 共 170+ 个品牌。
 */
object CarLogoData {
    val items = listOf(
        // 德国
        CarLogo("大众", "VW", "德国", "大众"),
        CarLogo("奥迪", "Audi", "德国", "豪华"),
        CarLogo("宝马", "BMW", "德国", "豪华"),
        CarLogo("奔驰", "Benz", "德国", "豪华"),
        CarLogo("迈巴赫", "Maybach", "德国", "超豪华"),
        CarLogo("保时捷", "Porsche", "德国", "超跑"),
        CarLogo("欧宝", "Opel", "德国", "大众"),
        CarLogo("斯柯达", "Skoda", "捷克", "大众"),
        CarLogo("西雅特", "Seat", "西班牙", "大众"),
        CarLogo("库普拉", "Cupra", "西班牙", "性能"),
        CarLogo("布加迪", "Bugatti", "法国", "超跑"),
        CarLogo("宝沃", "Borgward", "德国", "豪华"),
        CarLogo("曼恩", "MAN", "德国", "商用车"),
        CarLogo("尼奥普兰", "Neoplan", "德国", "客车"),
        CarLogo("阿尔宾娜", "Alpina", "德国", "性能"),
        CarLogo("威兹曼", "Wiesmann", "德国", "跑车"),
        // 日本
        CarLogo("丰田", "Toyota", "日本", "大众"),
        CarLogo("本田", "Honda", "日本", "大众"),
        CarLogo("日产", "Nissan", "日本", "大众"),
        CarLogo("马自达", "Mazda", "日本", "大众"),
        CarLogo("三菱", "Mitsubishi", "日本", "大众"),
        CarLogo("斯巴鲁", "Subaru", "日本", "性能"),
        CarLogo("铃木", "Suzuki", "日本", "大众"),
        CarLogo("雷克萨斯", "Lexus", "日本", "豪华"),
        CarLogo("英菲尼迪", "Infiniti", "日本", "豪华"),
        CarLogo("讴歌", "Acura", "日本", "豪华"),
        CarLogo("大发", "Daihatsu", "日本", "小型车"),
        CarLogo("五十铃", "Isuzu", "日本", "商用车"),
        CarLogo("日野", "Hino", "日本", "商用车"),
        CarLogo("光冈", "Mitsuoka", "日本", "个性"),
        CarLogo("速霸", "Tom's", "日本", "改装"),
        // 美国
        CarLogo("福特", "Ford", "美国", "大众"),
        CarLogo("雪佛兰", "Chevy", "美国", "大众"),
        CarLogo("别克", "Buick", "美国", "大众"),
        CarLogo("凯迪拉克", "Cadillac", "美国", "豪华"),
        CarLogo("GMC", "GMC", "美国", "皮卡"),
        CarLogo("克莱斯勒", "Chrysler", "美国", "大众"),
        CarLogo("道奇", "Dodge", "美国", "性能"),
        CarLogo("Jeep", "Jeep", "美国", "越野"),
        CarLogo("林肯", "Lincoln", "美国", "豪华"),
        CarLogo("特斯拉", "Tesla", "美国", "新能源"),
        CarLogo("悍马", "Hummer", "美国", "越野"),
        CarLogo("庞蒂亚克", "Pontiac", "美国", "经典"),
        CarLogo("奥兹莫比尔", "Oldsmobile", "美国", "经典"),
        CarLogo("土星", "Saturn", "美国", "经典"),
        CarLogo("里维安", "Rivian", "美国", "新能源"),
        CarLogo("路西德", "Lucid", "美国", "新能源"),
        CarLogo("菲斯克", "Fisker", "美国", "新能源"),
        CarLogo("赛麟", "Saleen", "美国", "超跑"),
        CarLogo("轩尼诗", "Hennessey", "美国", "超跑"),
        CarLogo("威利斯", "Willys", "美国", "越野"),
        // 中国
        CarLogo("比亚迪", "BYD", "中国", "新能源"),
        CarLogo("吉利", "Geely", "中国", "大众"),
        CarLogo("长城", "GWM", "中国", "SUV"),
        CarLogo("奇瑞", "Chery", "中国", "大众"),
        CarLogo("长安", "Changan", "中国", "大众"),
        CarLogo("红旗", "Hongqi", "中国", "豪华"),
        CarLogo("蔚来", "NIO", "中国", "新能源"),
        CarLogo("小鹏", "XPeng", "中国", "新能源"),
        CarLogo("理想", "Li Auto", "中国", "新能源"),
        CarLogo("领克", "Lynk", "中国", "年轻"),
        CarLogo("极氪", "Zeekr", "中国", "新能源"),
        CarLogo("岚图", "Voyah", "中国", "新能源"),
        CarLogo("阿维塔", "Avatr", "中国", "新能源"),
        CarLogo("深蓝", "Deepal", "中国", "新能源"),
        CarLogo("埃安", "Aion", "中国", "新能源"),
        CarLogo("哪吒", "Neta", "中国", "新能源"),
        CarLogo("零跑", "Leapmotor", "中国", "新能源"),
        CarLogo("问界", "AITO", "中国", "新能源"),
        CarLogo("智己", "IM", "中国", "新能源"),
        CarLogo("极狐", "Arcfox", "中国", "新能源"),
        CarLogo("高合", "HiPhi", "中国", "新能源"),
        CarLogo("威马", "WM", "中国", "新能源"),
        CarLogo("星途", "Exeed", "中国", "高端"),
        CarLogo("捷途", "Jetour", "中国", "SUV"),
        CarLogo("魏牌", "WEY", "中国", "高端"),
        CarLogo("坦克", "Tank", "中国", "越野"),
        CarLogo("哈弗", "Haval", "中国", "SUV"),
        CarLogo("欧拉", "ORA", "中国", "新能源"),
        CarLogo("五菱", "Wuling", "中国", "大众"),
        CarLogo("宝骏", "Baojun", "中国", "大众"),
        CarLogo("荣威", "Roewe", "中国", "大众"),
        CarLogo("名爵", "MG", "中国", "运动"),
        CarLogo("大通", "Maxus", "中国", "商用车"),
        CarLogo("东风", "Dongfeng", "中国", "大众"),
        CarLogo("一汽", "FAW", "中国", "大众"),
        CarLogo("奔腾", "Bestune", "中国", "大众"),
        CarLogo("广汽传祺", "Trumpchi", "中国", "大众"),
        CarLogo("江淮", "JAC", "中国", "大众"),
        CarLogo("江铃", "JMC", "中国", "商用车"),
        CarLogo("众泰", "Zotye", "中国", "大众"),
        CarLogo("陆风", "Landwind", "中国", "SUV"),
        CarLogo("海马", "Haima", "中国", "大众"),
        CarLogo("东南", "Soueast", "中国", "大众"),
        CarLogo("中华", "Brilliance", "中国", "大众"),
        CarLogo("观致", "Qoros", "中国", "大众"),
        CarLogo("纳智捷", "Luxgen", "中国台湾", "大众"),
        CarLogo("力帆", "Lifan", "中国", "大众"),
        CarLogo("猎豹", "Leopaard", "中国", "SUV"),
        CarLogo("汉腾", "Hanteng", "中国", "SUV"),
        CarLogo("斯威", "SWM", "中国", "SUV"),
        CarLogo("凯翼", "Cowin", "中国", "大众"),
        CarLogo("知豆", "Zhidou", "中国", "微型车"),
        CarLogo("云度", "Yudo", "中国", "新能源"),
        CarLogo("前途", "Qiantu", "中国", "跑车"),
        CarLogo("游侠", "Youxia", "中国", "新能源"),
        CarLogo("拜腾", "Byton", "中国", "新能源"),
        CarLogo("赛力斯", "Seres", "中国", "新能源"),
        CarLogo("创维汽车", "Skyworth", "中国", "新能源"),
        CarLogo("小米汽车", "Xiaomi", "中国", "新能源"),
        CarLogo("极越", "Jiyue", "中国", "新能源"),
        CarLogo("极石", "Polestones", "中国", "新能源"),
        CarLogo("仰望", "Yangwang", "中国", "超豪华"),
        CarLogo("方程豹", "Fangchengbao", "中国", "越野"),
        CarLogo("腾势", "Denza", "中国", "新能源"),
        CarLogo("智界", "Zhijie", "中国", "新能源"),
        CarLogo("享界", "Xiangjie", "中国", "新能源"),
        CarLogo("乐道", "Onvo", "中国", "新能源"),
        CarLogo("萤火虫", "Firefly", "中国", "新能源"),
        // 韩国
        CarLogo("现代", "Hyundai", "韩国", "大众"),
        CarLogo("起亚", "Kia", "韩国", "大众"),
        CarLogo("捷尼赛思", "Genesis", "韩国", "豪华"),
        CarLogo("双龙", "SsangYong", "韩国", "SUV"),
        CarLogo("大宇", "Daewoo", "韩国", "经典"),
        // 法国
        CarLogo("标致", "Peugeot", "法国", "大众"),
        CarLogo("雪铁龙", "Citroen", "法国", "大众"),
        CarLogo("雷诺", "Renault", "法国", "大众"),
        CarLogo("DS", "DS", "法国", "豪华"),
        CarLogo("阿尔派", "Alpine", "法国", "跑车"),
        CarLogo("文图瑞", "Venturi", "法国", "跑车"),
        // 意大利
        CarLogo("法拉利", "Ferrari", "意大利", "超跑"),
        CarLogo("兰博基尼", "Lambo", "意大利", "超跑"),
        CarLogo("玛莎拉蒂", "Maserati", "意大利", "豪华"),
        CarLogo("阿尔法·罗密欧", "Alfa", "意大利", "运动"),
        CarLogo("菲亚特", "Fiat", "意大利", "大众"),
        CarLogo("帕加尼", "Pagani", "意大利", "超跑"),
        CarLogo("蓝旗亚", "Lancia", "意大利", "经典"),
        CarLogo("阿巴斯", "Abarth", "意大利", "性能"),
        CarLogo("依维柯", "Iveco", "意大利", "商用车"),
        CarLogo("阿尔法", "Alfa", "意大利", "运动"),
        CarLogo("杜卡迪", "Ducati", "意大利", "摩托"),
        // 英国
        CarLogo("劳斯莱斯", "RR", "英国", "超豪华"),
        CarLogo("宾利", "Bentley", "英国", "超豪华"),
        CarLogo("迈凯伦", "McLaren", "英国", "超跑"),
        CarLogo("阿斯顿·马丁", "Aston", "英国", "豪华"),
        CarLogo("路虎", "Land Rover", "英国", "越野"),
        CarLogo("捷豹", "Jaguar", "英国", "豪华"),
        CarLogo("MINI", "MINI", "英国", "小型车"),
        CarLogo("路特斯", "Lotus", "英国", "跑车"),
        CarLogo("摩根", "Morgan", "英国", "复古"),
        CarLogo("罗孚", "Rover", "英国", "经典"),
        CarLogo("诺布尔", "Noble", "英国", "跑车"),
        CarLogo("卡特汉姆", "Caterham", "英国", "跑车"),
        CarLogo("阿斯卡里", "Ascari", "英国", "跑车"),
        CarLogo("凯旋", "Triumph", "英国", "摩托"),
        CarLogo("沃克斯豪尔", "Vauxhall", "英国", "大众"),
        // 瑞典 / 欧洲其他
        CarLogo("沃尔沃", "Volvo", "瑞典", "豪华"),
        CarLogo("极星", "Polestar", "瑞典", "新能源"),
        CarLogo("萨博", "Saab", "瑞典", "经典"),
        CarLogo("科尼赛克", "Koenigsegg", "瑞典", "超跑"),
        CarLogo("斯堪尼亚", "Scania", "瑞典", "商用车"),
        CarLogo("达契亚", "Dacia", "罗马尼亚", "大众"),
        CarLogo("太脱拉", "Tatra", "捷克", "商用车"),
        CarLogo("拉达", "Lada", "俄罗斯", "大众"),
        CarLogo("嘎斯", "GAZ", "俄罗斯", "商用车"),
        CarLogo("卡玛斯", "Kamaz", "俄罗斯", "商用车"),
        CarLogo("达夫", "DAF", "荷兰", "商用车"),
        CarLogo("世爵", "Spyker", "荷兰", "超跑"),
        CarLogo("Togg", "Togg", "土耳其", "新能源"),
        // 印度 / 亚洲其他
        CarLogo("塔塔", "Tata", "印度", "大众"),
        CarLogo("马恒达", "Mahindra", "印度", "SUV"),
        CarLogo("阿斯霍克雷兰德", "Ashok", "印度", "商用车"),
        CarLogo("宝腾", "Proton", "马来西亚", "大众"),
        CarLogo("VinFast", "VinFast", "越南", "新能源"),
        CarLogo("现代起亚", "HKG", "韩国", "大众"),
        // 摩托 / 其他
        CarLogo("哈雷戴维森", "Harley", "美国", "摩托"),
        CarLogo("宝马摩托", "BMW M", "德国", "摩托"),
        CarLogo("KTM", "KTM", "奥地利", "摩托"),
        CarLogo("雅马哈", "Yamaha", "日本", "摩托"),
        CarLogo("川崎", "Kawasaki", "日本", "摩托"),
        CarLogo("阿普利亚", "Aprilia", "意大利", "摩托"),
        CarLogo("奥古斯塔", "MV", "意大利", "摩托"),
        CarLogo("皇家恩菲尔德", "RE", "印度", "摩托")
    )
}
