package com.jisuanyusuiji.toolbox.tools.knowledge

data class FormulaItem(
    /** 分类（教材类公式为书名，如“高等数学上”） */
    val category: String,
    val name: String,
    val expression: String,
    val note: String,
    val level: String = "通用",
    /** 章节（大学教材公式用于二级筛选，可空） */
    val chapter: String = ""
)

object FormulaData {
    val all: List<FormulaItem> = listOf(
        // ---------- 数学 · 代数 ----------
        FormulaItem("代数", "平方差公式", "a^2 - b^2 = (a+b)(a-b)", "用于因式分解与简化运算"),
        FormulaItem("代数", "完全平方公式", "(a±b)^2 = a^2 ± 2ab + b^2", "展开与配方常用"),
        FormulaItem("代数", "一元二次求根公式", "x = (-b ± √(b^2-4ac)) / 2a", "Δ=b^2-4ac；Δ>0两实根，Δ=0重根，Δ<0共轭复根"),
        FormulaItem("代数", "判别式", "Δ = b^2 - 4ac", "判断一元二次方程根的情况"),
        FormulaItem("代数", "韦达定理", "x_1+x_2 = -b/a，x_1 x_2 = c/a", "根与系数的关系"),
        FormulaItem("代数", "指数运算法则", "a^m·a^n = a^(m+n)，(a^m)^n = a^(mn)", "同底数幂运算"),
        FormulaItem("代数", "对数运算法则", "log_a(MN) = log_a M + log_a N", "乘变加、除变减、幂提前"),
        FormulaItem("代数", "对数除法法则", "log_a(M/N) = log_a M - log_a N", "对数运算"),
        FormulaItem("代数", "对数幂法则", "log_a(M^n) = n·log_a M", "对数运算"),
        FormulaItem("代数", "换底公式", "log_a b = log_c b / log_c a", "任意底数对数互化"),
        FormulaItem("代数", "阶乘", "n! = n×(n-1)×…×1", "规定 0!=1"),
        FormulaItem("代数", "排列数", "A(n,m) = n! / (n-m)!", "从 n 个不同元素取 m 个排列"),
        FormulaItem("代数", "组合数", "C(n,m) = n! / [m!(n-m)!]", "从 n 个不同元素取 m 个组合"),
        FormulaItem("代数", "组合数性质", "C(n,m) = C(n,n-m)", "对称性"),
        FormulaItem("代数", "二项式定理", "(a+b)^n = Σ C(n,k)a^(n-k) b^k", "k 从 0 到 n"),
        FormulaItem("代数", "二项式通项", "T_(k+1) = C(n,k)a^(n-k) b^k", "展开式第 k+1 项"),
        FormulaItem("代数", "等差数列通项", "a_n = a_1 + (n-1)d", "d 为公差"),
        FormulaItem("代数", "等差数列求和", "S_n = n(a_1+a_n)/2 = na_1 + n(n-1)d/2", "前 n 项和"),
        FormulaItem("代数", "等比数列通项", "a_n = a_1 q^(n-1)", "q 为公比"),
        FormulaItem("代数", "等比数列求和", "S_n = a_1(1-q^n)/(1-q) (q≠1)", "q=1 时为 na_1"),
        FormulaItem("代数", "无穷等比级数", "S = a_1/(1-q)，|q|<1", "级数收敛条件"),
        FormulaItem("代数", "均值不等式", "a+b ≥ 2√(ab) (a,b>0)", "当且仅当 a=b 取等号"),
        FormulaItem("代数", "柯西不等式", "(Σa_i b_i)^2 ≤ (Σa_i^2)(Σb_i^2)", "向量形式与代数形式"),
        FormulaItem("代数", "复数模", "|a+bi| = √(a^2+b^2)", "复数到原点的距离"),
        FormulaItem("代数", "复数乘法", "(a+bi)(c+di) = (ac-bd) + (ad+bc)i", "复数运算"),
        FormulaItem("代数", "欧拉公式", "e^(iθ) = cosθ + i·sinθ", "复指数与三角函数的桥梁"),
        FormulaItem("代数", "棣莫弗定理", "[r(cosθ+isinθ)]^n = r^n(cos nθ + i sin nθ)", "复数乘方"),

        // ---------- 数学 · 三角 ----------
        FormulaItem("三角", "同角平方关系", "sin^2α + cos^2α = 1", "三角函数基本恒等式"),
        FormulaItem("三角", "商数关系", "tanα = sinα / cosα", "cosα ≠ 0"),
        FormulaItem("三角", "两角和正弦", "sin(α+β) = sinαcosβ + cosαsinβ", "和角公式"),
        FormulaItem("三角", "两角和余弦", "cos(α+β) = cosαcosβ - sinαsinβ", "和角公式"),
        FormulaItem("三角", "两角和正切", "tan(α+β) = (tanα+tanβ)/(1-tanαtanβ)", "分母不为 0"),
        FormulaItem("三角", "二倍角正弦", "sin2α = 2sinαcosα", "倍角公式"),
        FormulaItem("三角", "二倍角余弦", "cos2α = cos^2α - sin^2α = 1-2sin^2α = 2cos^2α-1", "三种等价形式"),
        FormulaItem("三角", "半角公式", "sin^2(α/2) = (1-cosα)/2", "降幂公式"),
        FormulaItem("三角", "辅助角公式", "a sinx + b cosx = √(a^2+b^2) sin(x+φ)", "tanφ = b/a"),
        FormulaItem("三角", "积化和差", "sinαcosβ = 1/2[sin(α+β)+sin(α-β)]", "积化和差"),
        FormulaItem("三角", "和差化积", "sinα+sinβ = 2sin((α+β)/2)cos((α-β)/2)", "和差化积"),
        FormulaItem("三角", "正弦定理", "a/sinA = b/sinB = c/sinC = 2R", "R 为外接圆半径"),
        FormulaItem("三角", "余弦定理", "a^2 = b^2 + c^2 - 2bc·cosA", "已知两边及夹角求第三边"),
        FormulaItem("三角", "三角形面积（两边夹角）", "S = 1/2ab·sinC", "已知两边 a、b 及其夹角 C"),
        FormulaItem("三角", "海伦公式", "S = √[p(p-a)(p-b)(p-c)]", "p = (a+b+c)/2"),

        // ---------- 数学 · 几何 ----------
        FormulaItem("几何", "圆周长", "C = 2πr = πd", "r 半径，d 直径"),
        FormulaItem("几何", "圆面积", "S = πr^2", "圆面积公式"),
        FormulaItem("几何", "扇形弧长", "l = rθ (θ 为弧度)", "θ = nπ/180 时 l = nπr/180"),
        FormulaItem("几何", "扇形面积", "S = 1/2lr = 1/2r^2θ", "θ 为弧度"),
        FormulaItem("几何", "椭圆面积", "S = πab", "a、b 为半长轴、半短轴"),
        FormulaItem("几何", "球体积", "V = (4/3)πr^3", "半径为 r"),
        FormulaItem("几何", "球表面积", "S = 4πr^2", "半径为 r"),
        FormulaItem("几何", "圆柱体积", "V = πr^2 h", "底面积 × 高"),
        FormulaItem("几何", "圆柱侧面积", "S侧 = 2πrh", "不含上下底"),
        FormulaItem("几何", "圆柱表面积", "S = 2πr^2 + 2πrh", "含上下底"),
        FormulaItem("几何", "圆锥体积", "V = (1/3)πr^2 h", "底面积 × 高 ÷ 3"),
        FormulaItem("几何", "圆锥侧面积", "S侧 = πrl", "l 为母线长"),
        FormulaItem("几何", "圆台体积", "V = (1/3)πh(R^2+Rr+r^2)", "R、r 为上下底半径"),
        FormulaItem("几何", "棱柱体积", "V = S底 × h", "底面积 × 高"),
        FormulaItem("几何", "棱锥体积", "V = (1/3)S底 × h", "底面积 × 高 ÷ 3"),
        FormulaItem("几何", "三角形内切圆半径", "r = S / p", "p 为半周长"),
        FormulaItem("几何", "三角形外接圆半径", "R = abc / (4S)", "与正弦定理一致"),
        FormulaItem("几何", "正多边形内角和", "(n-2) × 180°", "n 为边数"),
        FormulaItem("几何", "正多边形外角和", "360°", "任意凸多边形外角和"),
        FormulaItem("几何", "多边形对角线数", "n(n-3)/2", "n 为边数"),

        // ---------- 数学 · 解析几何 ----------
        FormulaItem("解析几何", "两点间距离", "d = √[(x_2-x_1)^2 + (y_2-y_1)^2]", "平面直角坐标系"),
        FormulaItem("解析几何", "线段中点", "M((x_1+x_2)/2, (y_1+y_2)/2)", "中点坐标"),
        FormulaItem("解析几何", "直线斜率", "k = (y_2-y_1)/(x_2-x_1)", "x_1 ≠ x_2"),
        FormulaItem("解析几何", "点到直线距离", "d = |Ax_0+By_0+C| / √(A^2+B^2)", "直线 Ax+By+C=0"),
        FormulaItem("解析几何", "两直线平行条件", "A_1/A_2 = B_1/B_2 ≠ C_1/C_2", "或斜率相等"),
        FormulaItem("解析几何", "两直线垂直条件", "A_1 A_2 + B_1 B_2 = 0", "或 k_1 k_2 = -1"),
        FormulaItem("解析几何", "圆的标准方程", "(x-a)^2 + (y-b)^2 = r^2", "圆心 (a,b)，半径 r"),
        FormulaItem("解析几何", "圆的一般方程", "x^2 + y^2 + Dx + Ey + F = 0", "D^2+E^2-4F>0 时表示圆"),
        FormulaItem("解析几何", "椭圆标准方程", "x^2/a^2 + y^2/b^2 = 1", "a>b>0，焦距 c^2=a^2-b^2"),
        FormulaItem("解析几何", "双曲线标准方程", "x^2/a^2 - y^2/b^2 = 1", "渐近线 y = ±(b/a)x"),
        FormulaItem("解析几何", "抛物线标准方程", "y^2 = 2px", "焦点 (p/2, 0)"),

        // ---------- 数学 · 微积分 ----------
        FormulaItem("微积分", "导数定义", "f'(x) = lim(Δx→0) [f(x+Δx)-f(x)]/Δx", "瞬时变化率"),
        FormulaItem("微积分", "幂函数导数", "(x^n)' = n·x^(n-1)", "n 为实数"),
        FormulaItem("微积分", "正弦导数", "(sinx)' = cosx", "基本导数公式"),
        FormulaItem("微积分", "余弦导数", "(cosx)' = -sinx", "基本导数公式"),
        FormulaItem("微积分", "指数导数", "(e^x)' = e^x", "自然指数"),
        FormulaItem("微积分", "对数导数", "(lnx)' = 1/x", "x > 0"),
        FormulaItem("微积分", "乘积求导", "(uv)' = u'v + uv'", "乘积法则"),
        FormulaItem("微积分", "商求导", "(u/v)' = (u'v - uv') / v^2", "v ≠ 0"),
        FormulaItem("微积分", "复合函数求导", "dy/dx = dy/du · du/dx", "链式法则"),
        FormulaItem("微积分", "牛顿-莱布尼茨公式", "∫_a^b f(x)dx = F(b) - F(a)", "定积分计算核心公式"),
        FormulaItem("微积分", "分部积分", "∫u dv = uv - ∫v du", "处理乘积型积分"),
        FormulaItem("微积分", "幂函数积分", "∫x^n dx = x^(n+1)/(n+1) + C (n≠-1)", "不定积分"),
        FormulaItem("微积分", "1/x 积分", "∫(1/x)dx = ln|x| + C", "x ≠ 0"),
        FormulaItem("微积分", "旋转体体积", "V = π∫_a^b [f(x)]^2 dx", "绕 x 轴旋转"),
        FormulaItem("微积分", "洛必达法则", "lim f/g = lim f'/g'", "0/0 或 ∞/∞ 型"),
        FormulaItem("微积分", "泰勒公式", "f(x) = Σ f^(n)(x_0)(x-x_0)^n/n!", "在 x_0 处展开"),
        FormulaItem("微积分", "欧拉公式（复分析）", "e^(ix) = cosx + i·sinx", "连接指数与三角"),

        // ---------- 数学 · 概率统计 ----------
        FormulaItem("概率统计", "古典概率", "P(A) = 有利结果数 / 总结果数", "等可能事件"),
        FormulaItem("概率统计", "条件概率", "P(A|B) = P(AB) / P(B)", "P(B) > 0"),
        FormulaItem("概率统计", "全概率公式", "P(A) = Σ P(B_i)P(A|B_i)", "完备事件组"),
        FormulaItem("概率统计", "贝叶斯公式", "P(B_i|A) = P(B_i)P(A|B_i) / ΣP(B_j)P(A|B_j)", "后验概率"),
        FormulaItem("概率统计", "数学期望", "E(X) = Σ x_i p_i", "离散型随机变量"),
        FormulaItem("概率统计", "方差", "D(X) = E(X^2) - [E(X)]^2", "衡量离散程度"),
        FormulaItem("概率统计", "二项分布", "P(X=k) = C(n,k)p^k(1-p)^(n-k)", "n 次独立重复试验"),
        FormulaItem("概率统计", "正态分布", "f(x) = 1/(σ√(2π))·e^(-(x-μ)^2/(2σ^2))", "均值 μ、标准差 σ"),
        FormulaItem("概率统计", "泊松分布", "P(X=k) = λ^k e^-λ / k!", "稀有事件计数"),

        // ---------- 物理 · 力学 ----------
        FormulaItem("力学", "平均速度", "v = Δx / Δt", "位移与时间之比"),
        FormulaItem("力学", "加速度", "a = Δv / Δt", "速度变化率"),
        FormulaItem("力学", "匀变速速度", "v = v_0 + at", "匀变速直线运动"),
        FormulaItem("力学", "匀变速位移", "x = v_0 t + 1/2at^2", "匀变速直线运动"),
        FormulaItem("力学", "速度位移关系", "v^2 - v_0^2 = 2ax", "不含时间的公式"),
        FormulaItem("力学", "牛顿第二定律", "F = ma", "合外力 = 质量 × 加速度"),
        FormulaItem("力学", "重力", "G = mg", "g ≈ 9.8 m/s^2"),
        FormulaItem("力学", "摩擦力", "f = μN", "μ 为动摩擦因数"),
        FormulaItem("力学", "胡克定律", "F = kx", "弹性限度内"),
        FormulaItem("力学", "万有引力", "F = G·m_1 m_2 / r^2", "G = 6.674×10^-11 N·m^2/kg^2"),
        FormulaItem("力学", "圆周运动向心力", "F = mv^2/r = mω^2 r", "指向圆心"),
        FormulaItem("力学", "线速度与角速度", "v = ωr", "圆周运动"),
        FormulaItem("力学", "功", "W = Fs·cosθ", "力与位移夹角 θ"),
        FormulaItem("力学", "功率", "P = W/t = Fv", "平均或瞬时功率"),
        FormulaItem("力学", "动能", "E_k = 1/2mv^2", "运动物体的能量"),
        FormulaItem("力学", "重力势能", "E_p = mgh", "相对于参考平面"),
        FormulaItem("力学", "弹性势能", "E_p = 1/2kx^2", "弹簧形变储存的能量"),
        FormulaItem("力学", "动量", "p = mv", "矢量"),
        FormulaItem("力学", "冲量", "I = FΔt = Δp", "动量定理"),
        FormulaItem("力学", "动量守恒", "m_1 v_1 + m_2 v_2 = m_1 v_1' + m_2 v_2'", "系统合外力为零"),
        FormulaItem("力学", "机械能守恒", "E_(k1) + E_(p1) = E_(k2) + E_(p2)", "只有重力/弹力做功"),
        FormulaItem("力学", "压强", "p = F/S", "单位面积压力"),
        FormulaItem("力学", "液体压强", "p = ρgh", "液体内部压强"),
        FormulaItem("力学", "浮力", "F浮 = ρ液gV排", "阿基米德原理"),
        FormulaItem("力学", "杠杆平衡", "F_1 L_1 = F_2 L_2", "力矩平衡"),

        // ---------- 物理 · 热学 ----------
        FormulaItem("热学", "热量", "Q = cmΔt", "吸放热计算"),
        FormulaItem("热学", "热值", "Q = qm", "燃料完全燃烧放热"),
        FormulaItem("热学", "理想气体状态方程", "pV = nRT", "R = 8.314 J/(mol·K)"),
        FormulaItem("热学", "玻意耳定律", "p_1 V_1 = p_2 V_2", "等温过程"),
        FormulaItem("热学", "查理定律", "p_1/T_1 = p_2/T_2", "等容过程"),
        FormulaItem("热学", "盖-吕萨克定律", "V_1/T_1 = V_2/T_2", "等压过程"),
        FormulaItem("热学", "热力学第一定律", "ΔU = Q + W", "约定：系统吸热 Q>0，外界对系统做功 W>0（两种教材约定都常见）"),
        FormulaItem("热学", "热机效率", "η = W有 / Q总 × 100%", "有用功与总热量之比"),
        FormulaItem("热学", "卡诺效率", "η = 1 - T冷/T热", "理想热机上限"),

        // ---------- 物理 · 电磁学 ----------
        FormulaItem("电磁学", "库仑定律", "F = k·q_1 q_2 / r^2", "k = 9.0×10^9 N·m^2/C^2"),
        FormulaItem("电磁学", "电场强度", "E = F/q", "单位正电荷受力"),
        FormulaItem("电磁学", "点电荷场强", "E = kQ / r^2", "点电荷周围电场"),
        FormulaItem("电磁学", "电势", "U = W/q", "单位电荷的电势能"),
        FormulaItem("电磁学", "电容定义", "C = Q/U", "电容器储存电荷能力"),
        FormulaItem("电磁学", "平行板电容器", "C = εS / (4πkd)", "SI 中 4πk=1/ε_0，即 C=ε_0ε_rS/d；S 为极板正对面积，d 为板间距"),
        FormulaItem("电磁学", "欧姆定律", "I = U/R", "部分电路欧姆定律"),
        FormulaItem("电磁学", "电阻定律", "R = ρL/S", "ρ 为电阻率"),
        FormulaItem("电磁学", "电功率", "P = UI = I^2 R = U^2/R", "纯电阻电路"),
        FormulaItem("电磁学", "焦耳定律", "Q = I^2 Rt", "电流热效应"),
        FormulaItem("电磁学", "串联电路", "R = R_1 + R_2 + …，I 处处相等", "串联规律"),
        FormulaItem("电磁学", "并联电路", "1/R = 1/R_1 + 1/R_2 + …，U 处处相等", "并联规律"),
        FormulaItem("电磁学", "磁感应强度", "B = F / (IL)", "通电导线在磁场中受力"),
        FormulaItem("电磁学", "安培力", "F = BIL·sinθ", "通电导线在磁场中的受力"),
        FormulaItem("电磁学", "洛伦兹力", "F = qvB·sinθ", "运动电荷在磁场中的受力"),
        FormulaItem("电磁学", "法拉第电磁感应定律", "E = n·ΔΦ/Δt", "感应电动势"),
        FormulaItem("电磁学", "导体切割磁感线", "E = BLv", "平动切割"),
        FormulaItem("电磁学", "变压器", "U_1/U_2 = n_1/n_2", "理想变压器"),
        FormulaItem("电磁学", "交流有效值", "U = U_0/√2", "正弦交流电"),

        // ---------- 物理 · 波与光 ----------
        FormulaItem("波与光", "波速公式", "v = λf = λ/T", "波长 × 频率"),
        FormulaItem("波与光", "折射定律", "n_1 sinθ_1 = n_2 sinθ_2", "斯涅尔定律"),
        FormulaItem("波与光", "折射率", "n = c / v", "真空光速与介质光速之比"),
        FormulaItem("波与光", "全反射临界角", "sinC = 1/n", "光密到光疏"),
        FormulaItem("波与光", "薄透镜成像", "1/f = 1/u + 1/v", "成像公式"),
        FormulaItem("波与光", "放大率", "m = -v/u", "像距与物距之比"),
        FormulaItem("波与光", "光电效应", "E_k = hν - W_0", "爱因斯坦光电方程"),
        FormulaItem("波与光", "光子能量", "E = hν = hc/λ", "h 为普朗克常数"),
        FormulaItem("波与光", "德布罗意波长", "λ = h / p", "物质波"),
        FormulaItem("波与光", "氢原子能级", "E_n = -13.6 / n^2 eV", "玻尔模型"),

        // ---------- 物理 · 常用常数 ----------
        FormulaItem("常数", "重力加速度（地表）", "g ≈ 9.8 m/s^2", "粗略计算可取 10"),
        FormulaItem("常数", "万有引力常数", "G = 6.674×10^-11 N·m^2/kg^2", "引力常量"),
        FormulaItem("常数", "真空中光速", "c = 3.00×10^8 m/s", "宇宙速度上限"),
        FormulaItem("常数", "普朗克常数", "h = 6.626×10^-34 J·s", "量子力学基本常数"),
        FormulaItem("常数", "元电荷", "e = 1.602×10^-19 C", "基本电荷量"),
        FormulaItem("常数", "电子质量", "m_e = 9.109×10^-31 kg", "电子静止质量"),
        FormulaItem("常数", "阿伏伽德罗常数", "N_a = 6.022×10^(23) /mol", "1 mol 粒子数"),
        FormulaItem("常数", "玻尔兹曼常数", "k = 1.381×10^-23 J/K", "热力学常数"),
        FormulaItem("常数", "理想气体常数", "R = 8.314 J/(mol·K)", "理想气体方程常数"),
        FormulaItem("常数", "真空介电常数", "ε_0 = 8.854×10^-12 F/m", "电学常数"),
        FormulaItem("常数", "真空磁导率", "μ_0 = 4π×10^-7 N/A^2", "电磁学常数"),
        FormulaItem("常数", "标准大气压", "1 atm = 101325 Pa", "约 760 mmHg"),
        FormulaItem("常数", "绝对零度", "0 K = -273.15 ℃", "热力学温度下限")
    )
}
