package com.jisuanyusuiji.toolbox.tools.knowledge

/** 按小学 / 初中 / 高中 / 大学 / 考研 / 研究生阶段补充的数学与物理公式。 */
object FormulaDataExtra {
    val all: List<FormulaItem> = listOf(
        // 小学数学
        FormulaItem("小学数学", "长方形周长", "C = 2(a+b)", "a 长，b 宽", "小学"),
        FormulaItem("小学数学", "长方形面积", "S = ab", "长 × 宽", "小学"),
        FormulaItem("小学数学", "正方形周长", "C = 4a", "边长 × 4", "小学"),
        FormulaItem("小学数学", "正方形面积", "S = a²", "边长 × 边长", "小学"),
        FormulaItem("小学数学", "平行四边形面积", "S = ah", "底 × 高", "小学"),
        FormulaItem("小学数学", "三角形面积", "S = ah/2", "底 × 高 ÷ 2", "小学"),
        FormulaItem("小学数学", "梯形面积", "S = (a+b)h/2", "上底 + 下底 × 高 ÷ 2", "小学"),
        FormulaItem("小学数学", "圆周长", "C = πd = 2πr", "直径 × π", "小学"),
        FormulaItem("小学数学", "圆面积", "S = πr²", "半径平方 × π", "小学"),
        FormulaItem("小学数学", "长方体体积", "V = abc", "长 × 宽 × 高", "小学"),
        FormulaItem("小学数学", "正方体体积", "V = a³", "棱长立方", "小学"),
        FormulaItem("小学数学", "圆柱体积", "V = πr²h", "底面积 × 高", "小学"),
        FormulaItem("小学数学", "圆锥体积", "V = πr²h/3", "等底等高圆柱的 1/3", "小学"),
        FormulaItem("小学数学", "速度和", "s = (v₁+v₂)t", "相遇问题", "小学"),
        FormulaItem("小学数学", "速度差", "s = (v₁-v₂)t", "追及问题", "小学"),
        FormulaItem("小学数学", "路程公式", "s = vt", "速度 × 时间", "小学"),
        FormulaItem("小学数学", "总价公式", "总价 = 单价 × 数量", "购物问题", "小学"),
        FormulaItem("小学数学", "工作总量", "工作总量 = 效率 × 时间", "工程问题", "小学"),
        FormulaItem("小学数学", "百分数", "百分数 = 部分 ÷ 总数 × 100%", "比例与百分数", "小学"),
        FormulaItem("小学数学", "利息（简易）", "利息 = 本金 × 利率 × 时间", "小学简易利息", "小学"),

        // 初中数学
        FormulaItem("初中数学", "平方差公式", "(a+b)(a-b) = a²-b²", "整式乘法", "初中"),
        FormulaItem("初中数学", "完全平方公式", "(a±b)² = a²±2ab+b²", "整式乘法", "初中"),
        FormulaItem("初中数学", "十字相乘法", "x²+(p+q)x+pq = (x+p)(x+q)", "因式分解", "初中"),
        FormulaItem("初中数学", "一元二次求根", "x = (-b±√(b²-4ac))/2a", "配方法与判别式", "初中"),
        FormulaItem("初中数学", "一次函数", "y = kx + b", "k 为斜率", "初中"),
        FormulaItem("初中数学", "反比例函数", "y = k/x", "k ≠ 0", "初中"),
        FormulaItem("初中数学", "二次函数顶点", "(-b/2a, (4ac-b²)/4a)", "抛物线顶点坐标", "初中"),
        FormulaItem("初中数学", "两点间距离", "d = √[(x₂-x₁)²+(y₂-y₁)²]", "平面直角坐标系", "初中"),
        FormulaItem("初中数学", "锐角三角函数", "sinA = 对边/斜边", "cosA = 邻边/斜边，tanA = 对边/邻边", "初中"),
        FormulaItem("初中数学", "特殊角三角函数", "sin30°=1/2，sin45°=√2/2，sin60°=√3/2", "特殊角取值", "初中"),
        FormulaItem("初中数学", "多边形内角和", "(n-2)×180°", "n 为边数", "初中"),
        FormulaItem("初中数学", "扇形面积", "S = nπr²/360", "n 为圆心角度数", "初中"),
        FormulaItem("初中数学", "弧长公式", "l = nπr/180", "n 为圆心角度数", "初中"),
        FormulaItem("初中数学", "方差（初中）", "s² = Σ(xᵢ-x̄)²/n", "衡量数据波动", "初中"),
        FormulaItem("初中物理", "速度", "v = s/t", "机械运动", "初中"),
        FormulaItem("初中物理", "密度", "ρ = m/V", "质量与体积之比", "初中"),
        FormulaItem("初中物理", "重力", "G = mg", "g ≈ 9.8 N/kg", "初中"),
        FormulaItem("初中物理", "压强", "p = F/S", "压力与受力面积之比", "初中"),
        FormulaItem("初中物理", "液体压强", "p = ρgh", "深度 h 处的压强", "初中"),
        FormulaItem("初中物理", "浮力", "F浮 = ρ液gV排", "阿基米德原理", "初中"),
        FormulaItem("初中物理", "功", "W = Fs", "力 × 沿力方向位移", "初中"),
        FormulaItem("初中物理", "功率", "P = W/t", "做功快慢", "初中"),
        FormulaItem("初中物理", "机械效率", "η = W有/W总 × 100%", "有用功占比", "初中"),
        FormulaItem("初中物理", "欧姆定律", "I = U/R", "电流与电压、电阻关系", "初中"),
        FormulaItem("初中物理", "电功率", "P = UI", "电流做功快慢", "初中"),
        FormulaItem("初中物理", "焦耳定律", "Q = I²Rt", "电流热效应", "初中"),
        FormulaItem("初中物理", "串联电阻", "R = R₁ + R₂", "串联电路", "初中"),
        FormulaItem("初中物理", "并联电阻", "1/R = 1/R₁ + 1/R₂", "并联电路", "初中"),
        FormulaItem("初中物理", "热量计算", "Q = cmΔt", "比热容公式", "初中"),
        FormulaItem("初中物理", "燃料热值", "Q = qm", "燃料完全燃烧放热", "初中"),

        // 高中数学
        FormulaItem("高中数学", "对数换底", "logₐb = lnb/lna", "任意底数互化", "高中"),
        FormulaItem("高中数学", "等比中项", "G² = ab", "G 为 a、b 的等比中项", "高中"),
        FormulaItem("高中数学", "等差数列求和", "Sₙ = n(a₁+aₙ)/2", "前 n 项和", "高中"),
        FormulaItem("高中数学", "等比数列求和", "Sₙ = a₁(1-qⁿ)/(1-q)", "q ≠ 1", "高中"),
        FormulaItem("高中数学", "正弦定理", "a/sinA = b/sinB = c/sinC = 2R", "解三角形", "高中"),
        FormulaItem("高中数学", "余弦定理", "c² = a²+b²-2ab·cosC", "解三角形", "高中"),
        FormulaItem("高中数学", "三角形面积", "S = ½ab·sinC", "两边夹角", "高中"),
        FormulaItem("高中数学", "两角和差", "sin(α±β) = sinαcosβ ± cosαsinβ", "三角恒等变换", "高中"),
        FormulaItem("高中数学", "二倍角", "sin2α = 2sinαcosα", "cos2α = cos²α-sin²α", "高中"),
        FormulaItem("高中数学", "辅助角", "a sinx + b cosx = √(a²+b²)sin(x+φ)", "tanφ = b/a", "高中"),
        FormulaItem("高中数学", "导数定义", "f'(x₀) = lim(Δx→0)Δy/Δx", "切线斜率", "高中"),
        FormulaItem("高中数学", "常见导数", "(xⁿ)'=nxⁿ⁻¹，(sinx)'=cosx，(eˣ)'=eˣ，(lnx)'=1/x", "基本求导公式", "高中"),
        FormulaItem("高中数学", "切线方程", "y-f(x₀) = f'(x₀)(x-x₀)", "在 x₀ 处切线", "高中"),
        FormulaItem("高中数学", "椭圆", "x²/a²+y²/b²=1，c²=a²-b²", "焦点在 x 轴", "高中"),
        FormulaItem("高中数学", "双曲线", "x²/a²-y²/b²=1，c²=a²+b²", "渐近线 y=±bx/a", "高中"),
        FormulaItem("高中数学", "抛物线", "y²=2px，焦点(p/2,0)", "准线 x=-p/2", "高中"),
        FormulaItem("高中数学", "点到直线距离", "d = |Ax₀+By₀+C|/√(A²+B²)", "直线 Ax+By+C=0", "高中"),
        FormulaItem("高中数学", "排列组合", "A(n,m)=n!/(n-m)!，C(n,m)=n!/[m!(n-m)!]", "计数原理", "高中"),
        FormulaItem("高中数学", "二项式定理", "(a+b)ⁿ = ΣC(n,k)aⁿ⁻ᵏbᵏ", "展开式", "高中"),
        FormulaItem("高中数学", "条件概率", "P(B|A) = P(AB)/P(A)", "概率基础", "高中"),
        FormulaItem("高中数学", "期望方差", "E(X)=Σxᵢpᵢ，D(X)=E(X²)-[E(X)]²", "随机变量", "高中"),
        FormulaItem("高中物理", "匀变速运动", "v=v₀+at，x=v₀t+½at²，v²-v₀²=2ax", "运动学三公式", "高中"),
        FormulaItem("高中物理", "牛顿第二定律", "F = ma", "合外力与加速度", "高中"),
        FormulaItem("高中物理", "圆周运动", "a = v²/r = ω²r，T = 2π/ω", "向心加速度", "高中"),
        FormulaItem("高中物理", "万有引力", "F = Gm₁m₂/r²", "天体运动", "高中"),
        FormulaItem("高中物理", "动能定理", "W合 = ΔEₖ = ½mv²-½mv₀²", "合外力做功", "高中"),
        FormulaItem("高中物理", "动量定理", "I = FΔt = Δp", "冲量与动量变化", "高中"),
        FormulaItem("高中物理", "动量守恒", "m₁v₁+m₂v₂ = m₁v₁'+m₂v₂'", "碰撞问题", "高中"),
        FormulaItem("高中物理", "电场强度", "E = F/q = kQ/r²", "点电荷电场", "高中"),
        FormulaItem("高中物理", "电势差", "U = W/q", "电场力做功", "高中"),
        FormulaItem("高中物理", "电容", "C = Q/U", "电容器", "高中"),
        FormulaItem("高中物理", "电阻定律", "R = ρL/S", "导体电阻", "高中"),
        FormulaItem("高中物理", "安培力", "F = BIL·sinθ", "通电导线在磁场中", "高中"),
        FormulaItem("高中物理", "洛伦兹力", "F = qvB·sinθ", "带电粒子在磁场中", "高中"),
        FormulaItem("高中物理", "法拉第电磁感应", "E = nΔΦ/Δt", "感应电动势", "高中"),
        FormulaItem("高中物理", "折射定律", "n = sinθ₁/sinθ₂ = c/v", "光的折射", "高中"),
        FormulaItem("高中物理", "光电效应", "Eₖ = hν - W₀", "爱因斯坦方程", "高中"),

        // 大学 / 考研数学
        FormulaItem("大学数学", "重要极限", "lim(x→0) sinx/x = 1，lim(x→∞)(1+1/x)ˣ = e", "高数基础", "大学"),
        FormulaItem("大学数学", "等价无穷小", "x~sinx~tanx~arcsinx~arctanx~ln(1+x)~eˣ-1", "x→0", "大学"),
        FormulaItem("大学数学", "洛必达法则", "lim f/g = lim f'/g'", "0/0 或 ∞/∞", "大学"),
        FormulaItem("大学数学", "泰勒展开", "f(x)=Σ f⁽ⁿ⁾(x₀)(x-x₀)ⁿ/n!", "函数逼近", "大学"),
        FormulaItem("大学数学", "麦克劳林展开", "eˣ=Σxⁿ/n!，sinx=Σ(-1)ⁿx²ⁿ⁺¹/(2n+1)!", "x₀=0 的泰勒展开", "大学"),
        FormulaItem("大学数学", "分部积分", "∫u dv = uv - ∫v du", "积分技巧", "大学"),
        FormulaItem("大学数学", "定积分性质", "∫ₐᵇf = -∫ᵦᵃf", "交换上下限变号", "大学"),
        FormulaItem("大学数学", "微积分基本定理", "∫ₐᵇf(x)dx = F(b)-F(a)", "牛顿-莱布尼茨公式", "大学"),
        FormulaItem("大学数学", "二阶行列式", "|a b; c d| = ad - bc", "线性代数", "大学"),
        FormulaItem("大学数学", "矩阵乘法", "(AB)ᵢⱼ = ΣAᵢₖBₖⱼ", "行乘列", "大学"),
        FormulaItem("大学数学", "逆矩阵", "A⁻¹ = A*/|A|", "A* 为伴随矩阵", "大学"),
        FormulaItem("大学数学", "特征值方程", "|A - λI| = 0", "求特征值", "大学"),
        FormulaItem("大学数学", "全概率公式", "P(A) = ΣP(Bᵢ)P(A|Bᵢ)", "概率论", "大学"),
        FormulaItem("大学数学", "贝叶斯公式", "P(Bᵢ|A) = P(Bᵢ)P(A|Bᵢ)/ΣP(Bⱼ)P(A|Bⱼ)", "后验概率", "大学"),
        FormulaItem("大学数学", "正态分布密度", "f(x)=1/(σ√(2π))e^(-(x-μ)²/2σ²)", "概率统计", "大学"),
        FormulaItem("大学数学", "中心极限定理", "(ΣXᵢ-nμ)/(σ√n) → N(0,1)", "大样本近似", "大学"),
        FormulaItem("大学数学", "方差性质", "D(aX+b)=a²D(X)", "随机变量", "大学"),
        FormulaItem("大学数学", "协方差", "Cov(X,Y)=E(XY)-E(X)E(Y)", "相关性度量", "大学"),
        FormulaItem("大学数学", "最小二乘", "b̂ = Σ(xᵢ-x̄)(yᵢ-ȳ)/Σ(xᵢ-x̄)²", "线性回归", "大学"),
        FormulaItem("大学数学", "梯度", "∇f = (∂f/∂x, ∂f/∂y, ∂f/∂z)", "多元微分", "考研"),
        FormulaItem("大学数学", "方向导数", "∂f/∂l = ∇f·l", "沿单位方向 l", "考研"),
        FormulaItem("大学数学", "二重积分极坐标", "∬f dxdy = ∬f r dr dθ", "极坐标变换", "考研"),
        FormulaItem("大学数学", "格林公式", "∮Pdx+Qdy = ∬(∂Q/∂x-∂P/∂y)dxdy", "曲线积分", "考研"),
        FormulaItem("大学数学", "高斯公式", "∯F·dS = ∭∇·F dV", "散度定理", "考研"),
        FormulaItem("大学数学", "斯托克斯公式", "∮F·dr = ∬(∇×F)·dS", "旋度定理", "考研"),
        FormulaItem("大学数学", "傅里叶级数", "f(x)=a₀/2+Σ(aₙcosnx+bₙsinnx)", "周期函数展开", "考研"),
        FormulaItem("大学数学", "拉普拉斯变换", "F(s)=∫₀^∞ f(t)e^(-st)dt", "工程数学", "考研"),
        FormulaItem("大学数学", "欧拉公式", "e^(iθ)=cosθ+isinθ", "复变函数", "考研"),
        FormulaItem("大学数学", "柯西积分公式", "f(z₀)=1/(2πi)∮f(z)/(z-z₀)dz", "复变函数", "考研"),

        // 大学物理 / 研究生
        FormulaItem("大学物理", "质点运动学", "v=dr/dt，a=dv/dt=d²r/dt²", "矢量形式", "大学"),
        FormulaItem("大学物理", "转动定律", "M = Jβ", "刚体定轴转动", "大学"),
        FormulaItem("大学物理", "转动动能", "Eₖ = ½Jω²", "刚体转动", "大学"),
        FormulaItem("大学物理", "角动量", "L = Jω = r×p", "角动量守恒", "大学"),
        FormulaItem("大学物理", "简谐振动", "x = A cos(ωt+φ)", "ω=√(k/m)", "大学"),
        FormulaItem("大学物理", "单摆周期", "T = 2π√(l/g)", "小角度摆动", "大学"),
        FormulaItem("大学物理", "波动方程", "y = A cos(ωt - kx)", "k=2π/λ", "大学"),
        FormulaItem("大学物理", "理想气体状态方程", "pV = nRT = NkT", "热学基础", "大学"),
        FormulaItem("大学物理", "热力学第一定律", "ΔU = Q + W", "能量守恒", "大学"),
        FormulaItem("大学物理", "热机效率", "η = 1 - Q₂/Q₁", "卡诺效率 η=1-T₂/T₁", "大学"),
        FormulaItem("大学物理", "熵变", "dS = dQ/T", "可逆过程", "大学"),
        FormulaItem("大学物理", "库仑定律", "F = kq₁q₂/r²", "静电场", "大学"),
        FormulaItem("大学物理", "高斯定理", "∮E·dS = Q/ε₀", "静电场", "大学"),
        FormulaItem("大学物理", "电势", "V = ∫E·dl", "电势与电场关系", "大学"),
        FormulaItem("大学物理", "电容储能", "W = ½CU²", "电容器能量", "大学"),
        FormulaItem("大学物理", "安培环路定理", "∮B·dl = μ₀I", "磁场", "大学"),
        FormulaItem("大学物理", "毕奥-萨伐尔定律", "dB = μ₀I dl×r̂/(4πr²)", "电流元磁场", "大学"),
        FormulaItem("大学物理", "电磁感应", "ε = -dΦ/dt", "法拉第定律", "大学"),
        FormulaItem("大学物理", "麦克斯韦方程组", "∇·E=ρ/ε₀，∇×B=μ₀J+μ₀ε₀∂E/∂t", "电磁场基本方程", "研究生"),
        FormulaItem("大学物理", "波动方程（电磁）", "∇²E = μ₀ε₀ ∂²E/∂t²", "光速 c=1/√(μ₀ε₀)", "研究生"),
        FormulaItem("大学物理", "薛定谔方程", "iħ∂Ψ/∂t = ĤΨ", "量子力学基本方程", "研究生"),
        FormulaItem("大学物理", "德布罗意关系", "λ = h/p，ν = E/h", "物质波", "研究生"),
        FormulaItem("大学物理", "海森堡不确定关系", "Δx·Δp ≥ ħ/2", "量子力学", "研究生"),
        FormulaItem("大学物理", "爱因斯坦质能方程", "E = mc²", "相对论", "研究生"),
        FormulaItem("大学物理", "洛伦兹变换", "x'=γ(x-vt)，t'=γ(t-vx/c²)", "狭义相对论", "研究生"),
        FormulaItem("大学物理", "玻尔兹曼分布", "P ∝ e^(-E/kT)", "统计物理", "研究生"),
        FormulaItem("大学物理", "普朗克公式", "E = hν", "能量量子化", "研究生")
    )
}
