package com.jisuanyusuiji.toolbox.tools.knowledge

data class ShortcutItem(
    val platform: String,
    val category: String,
    val level: String,
    val keys: String,
    val action: String
)

object ShortcutData {

    val items: List<ShortcutItem> = windows() + mac()

    private fun windows(): List<ShortcutItem> = listOf(
        // 基础操作
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + C", "复制"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + V", "粘贴"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + X", "剪切"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + Z", "撤销"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + Y", "恢复 / 重做"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + A", "全选"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + S", "保存"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + P", "打印"),
        ShortcutItem("Windows", "基础操作", "常用", "Ctrl + F", "查找"),
        ShortcutItem("Windows", "基础操作", "常用", "Alt + F4", "关闭当前程序"),
        ShortcutItem("Windows", "基础操作", "常用", "F1", "打开帮助"),
        ShortcutItem("Windows", "基础操作", "常用", "F2", "重命名所选项目"),
        ShortcutItem("Windows", "基础操作", "常用", "F5", "刷新当前窗口"),
        ShortcutItem("Windows", "基础操作", "常用", "Esc", "取消当前操作"),

        // 窗口与桌面
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + D", "显示 / 隐藏桌面"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + E", "打开文件资源管理器"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + I", "打开设置"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + L", "锁定电脑"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + R", "打开“运行”"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + S", "打开搜索"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Alt + Tab", "在打开的应用之间切换"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + Tab", "任务视图（虚拟桌面）"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + 左/右箭头", "窗口靠左 / 靠右分屏"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + 上箭头", "最大化当前窗口"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + 下箭头", "最小化 / 还原窗口"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + Home", "最小化除当前窗口外的所有窗口"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + M", "最小化所有窗口"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + Shift + M", "还原最小化的窗口"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Alt + Space", "打开当前窗口的系统菜单"),
        ShortcutItem("Windows", "窗口与桌面", "常用", "Win + ,", "临时偷看桌面（松开恢复）"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Win + Z", "打开窗口贴靠布局"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Win + Ctrl + D", "新建虚拟桌面"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Win + Ctrl + 左/右箭头", "切换虚拟桌面"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Win + Ctrl + F4", "关闭当前虚拟桌面"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Win + Shift + 左/右箭头", "把窗口移到另一显示器"),
        ShortcutItem("Windows", "窗口与桌面", "进阶", "Ctrl + Alt + Tab", "用方向键在应用间切换"),

        // 文件与资源管理器
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Ctrl + N", "打开新窗口"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Ctrl + Shift + N", "新建文件夹"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Ctrl + W", "关闭当前窗口"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Alt + Enter", "查看所选项目属性"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Alt + 左箭头", "后退"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Alt + 右箭头", "前进"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Alt + 上箭头", "返回上一级文件夹"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "F3", "在资源管理器中搜索"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "F4", "显示地址栏列表"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Shift + Delete", "永久删除（不进回收站）"),
        ShortcutItem("Windows", "文件与资源管理器", "常用", "Ctrl + 鼠标滚轮", "改变图标大小"),
        ShortcutItem("Windows", "文件与资源管理器", "进阶", "Ctrl + Shift + 数字", "按数字切换视图（详情/大图标等）"),
        ShortcutItem("Windows", "文件与资源管理器", "进阶", "Ctrl + Shift + E", "展开左侧导航栏所有文件夹"),
        ShortcutItem("Windows", "文件与资源管理器", "进阶", "Win + 数字键", "打开任务栏第 N 个应用"),
        ShortcutItem("Windows", "文件与资源管理器", "进阶", "Win + T", "循环切换任务栏应用"),
        ShortcutItem("Windows", "文件与资源管理器", "进阶", "Win + B", "定位到系统托盘通知区域"),

        // 文本编辑
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + B / I / U", "加粗 / 斜体 / 下划线"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + Home", "光标跳到文档开头"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + End", "光标跳到文档结尾"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + 左/右箭头", "按词移动光标"),
        ShortcutItem("Windows", "文本编辑", "常用", "Shift + 方向键", "逐字符选择"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + Shift + 方向键", "按词选择"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + Backspace", "删除前一个词"),
        ShortcutItem("Windows", "文本编辑", "常用", "Ctrl + Delete", "删除后一个词"),
        ShortcutItem("Windows", "文本编辑", "常用", "Shift + Home / End", "选择到行首 / 行尾"),
        ShortcutItem("Windows", "文本编辑", "进阶", "Ctrl + Shift + Home / End", "选择到文档开头 / 结尾"),
        ShortcutItem("Windows", "文本编辑", "进阶", "Shift + Enter", "换行但不开始新段落"),
        ShortcutItem("Windows", "文本编辑", "进阶", "Ctrl + Enter", "插入分页符（Word 等）"),

        // 浏览器
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + T", "新建标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + W", "关闭当前标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + Shift + T", "恢复刚关闭的标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + Tab", "切换到下一个标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + Shift + Tab", "切换到上一个标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + 1~8", "跳转到第 1~8 个标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + 9", "跳转到最后一个标签页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + D", "收藏当前网页"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + H", "打开历史记录"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + J", "打开下载记录"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + L", "定位到地址栏"),
        ShortcutItem("Windows", "浏览器", "常用", "Ctrl + R / F5", "刷新页面"),
        ShortcutItem("Windows", "浏览器", "进阶", "Ctrl + F5", "强制刷新（清除缓存）"),
        ShortcutItem("Windows", "浏览器", "进阶", "Ctrl + Shift + N", "打开无痕 / InPrivate 窗口"),
        ShortcutItem("Windows", "浏览器", "进阶", "Ctrl + Shift + Delete", "打开“清除浏览数据”"),
        ShortcutItem("Windows", "浏览器", "进阶", "Ctrl + 滚轮", "缩放页面"),
        ShortcutItem("Windows", "浏览器", "进阶", "Ctrl + 0", "恢复 100% 缩放"),
        ShortcutItem("Windows", "浏览器", "进阶", "F11", "全屏模式"),
        ShortcutItem("Windows", "浏览器", "进阶", "F12", "打开开发者工具"),

        // 截图与录屏
        ShortcutItem("Windows", "截图与录屏", "常用", "Win + Shift + S", "区域截图（保存到剪贴板）"),
        ShortcutItem("Windows", "截图与录屏", "常用", "PrintScreen", "全屏截图到剪贴板"),
        ShortcutItem("Windows", "截图与录屏", "常用", "Alt + PrintScreen", "截取当前窗口"),
        ShortcutItem("Windows", "截图与录屏", "进阶", "Win + PrintScreen", "全屏截图并自动保存"),
        ShortcutItem("Windows", "截图与录屏", "进阶", "Win + Alt + R", "开始 / 停止屏幕录制"),
        ShortcutItem("Windows", "截图与录屏", "进阶", "Win + G", "打开 Xbox Game Bar"),

        // 进阶与系统
        ShortcutItem("Windows", "进阶与系统", "进阶", "Ctrl + Shift + Esc", "直接打开任务管理器"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + X", "打开“快速链接”菜单（开始右键菜单）"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + V", "打开剪贴板历史"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + . 或 Win + ;", "打开 Emoji 表情面板"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + A", "打开快速设置（Wi-Fi/蓝牙等）"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + N", "打开通知中心"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + W", "打开小组件面板"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + P", "投影模式（复制/扩展屏幕）"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + K", "打开“连接”快速设置"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + Pause", "打开“系统属性”"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + Ctrl + Shift + B", "重置显卡驱动（黑屏急救）"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Ctrl + Shift + Enter", "在“运行”中以管理员身份运行命令"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Shift + 右键文件夹", "显示“在此处打开命令窗口/PowerShell”"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Alt + F8", "登录界面显示密码（旧版）"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + F", "打开反馈中心"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + U", "打开辅助功能设置"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + 加号 / 减号", "放大镜放大 / 缩小"),
        ShortcutItem("Windows", "进阶与系统", "进阶", "Win + Esc", "退出放大镜"),

        // 命令提示符 / Terminal
        ShortcutItem("Windows", "命令提示符", "进阶", "Ctrl + C", "终止当前命令"),
        ShortcutItem("Windows", "命令提示符", "进阶", "Ctrl + M", "进入标记模式（可复制）"),
        ShortcutItem("Windows", "命令提示符", "进阶", "Tab", "自动补全文件名 / 命令"),
        ShortcutItem("Windows", "命令提示符", "进阶", "F7", "查看命令历史记录"),
        ShortcutItem("Windows", "命令提示符", "进阶", "Alt + Enter", "CMD 全屏切换"),
        ShortcutItem("Windows", "命令提示符", "进阶", "Ctrl + Shift + 滚轮", "调整终端透明度（Windows Terminal）"),
        ShortcutItem("Windows", "命令提示符", "进阶", "Ctrl + Shift + P", "Windows Terminal 命令面板")
    )

    private fun mac(): List<ShortcutItem> = listOf(
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + C", "复制"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + V", "粘贴"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + X", "剪切"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + Z", "撤销"),
        ShortcutItem("macOS", "基础操作", "常用", "⇧ + ⌘ + Z", "重做"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + A", "全选"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + S", "保存"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + P", "打印"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + F", "查找"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + Space", "打开聚焦搜索（Spotlight）"),
        ShortcutItem("macOS", "基础操作", "常用", "⌘ + ,", "打开当前应用偏好设置"),
        ShortcutItem("macOS", "基础操作", "进阶", "⌥ + ⌘ + Space", "在访达中搜索"),

        // 窗口与访达
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + W", "关闭当前窗口"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + Q", "退出当前应用"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + M", "最小化窗口"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + H", "隐藏当前应用"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + Tab", "在应用之间切换"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + `", "在同一应用窗口间切换"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + N", "新建窗口 / 文件"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + Delete", "移到废纸篓"),
        ShortcutItem("macOS", "窗口与访达", "常用", "Space", "快速查看（Quick Look）"),
        ShortcutItem("macOS", "窗口与访达", "常用", "⌘ + 上箭头", "前往上一级文件夹"),
        ShortcutItem("macOS", "窗口与访达", "进阶", "⌥ + ⌘ + H", "隐藏除当前应用外的所有应用"),
        ShortcutItem("macOS", "窗口与访达", "进阶", "⌘ + Ctrl + F", "进入 / 退出全屏"),
        ShortcutItem("macOS", "窗口与访达", "进阶", "⇧ + ⌘ + .", "显示 / 隐藏隐藏文件"),
        ShortcutItem("macOS", "窗口与访达", "进阶", "⇧ + ⌘ + Delete", "清空废纸篓"),
        ShortcutItem("macOS", "窗口与访达", "进阶", "⌘ + 数字 1~4", "访达视图切换（图标/列表/分栏/画廊）"),

        // 文本编辑
        ShortcutItem("macOS", "文本编辑", "常用", "⌘ + B / I / U", "加粗 / 斜体 / 下划线"),
        ShortcutItem("macOS", "文本编辑", "常用", "⌘ + 左/右箭头", "跳到行首 / 行尾"),
        ShortcutItem("macOS", "文本编辑", "常用", "⌘ + 上/下箭头", "跳到文档开头 / 结尾"),
        ShortcutItem("macOS", "文本编辑", "常用", "⌥ + 左/右箭头", "按词移动光标"),
        ShortcutItem("macOS", "文本编辑", "常用", "⇧ + 方向键", "逐字符选择"),
        ShortcutItem("macOS", "文本编辑", "常用", "⌥ + Delete", "删除前一个词"),
        ShortcutItem("macOS", "文本编辑", "进阶", "⌥ + ⇧ + 方向键", "按词选择"),
        ShortcutItem("macOS", "文本编辑", "进阶", "⌘ + K", "插入链接（备忘录/邮件等）"),
        ShortcutItem("macOS", "文本编辑", "进阶", "⌃ + K", "删除到行尾"),

        // 浏览器
        ShortcutItem("macOS", "浏览器", "常用", "⌘ + T", "新建标签页"),
        ShortcutItem("macOS", "浏览器", "常用", "⌘ + W", "关闭当前标签页"),
        ShortcutItem("macOS", "浏览器", "常用", "⇧ + ⌘ + T", "恢复刚关闭的标签页"),
        ShortcutItem("macOS", "浏览器", "常用", "⌘ + L", "定位到地址栏"),
        ShortcutItem("macOS", "浏览器", "常用", "⌘ + R", "刷新页面"),
        ShortcutItem("macOS", "浏览器", "常用", "⌘ + D", "收藏当前网页"),
        ShortcutItem("macOS", "浏览器", "进阶", "⇧ + ⌘ + R", "强制刷新（清除缓存）"),
        ShortcutItem("macOS", "浏览器", "进阶", "⌘ + 1~8", "跳转到第 1~8 个标签页"),
        ShortcutItem("macOS", "浏览器", "进阶", "⌘ + 9", "跳转到最后一个标签页"),
        ShortcutItem("macOS", "浏览器", "进阶", "⇧ + ⌘ + N", "打开无痕窗口"),
        ShortcutItem("macOS", "浏览器", "进阶", "⌘ + 加号 / 减号", "页面放大 / 缩小"),
        ShortcutItem("macOS", "浏览器", "进阶", "⌘ + 0", "恢复 100% 缩放"),

        // 截图与系统
        ShortcutItem("macOS", "截图与系统", "常用", "⇧ + ⌘ + 3", "全屏截图"),
        ShortcutItem("macOS", "截图与系统", "常用", "⇧ + ⌘ + 4", "区域截图"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⇧ + ⌘ + 5", "截图 / 录屏工具栏"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⇧ + ⌘ + 4 + Space", "窗口截图"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⌃ + ⌘ + Q", "锁定屏幕"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⌥ + ⌘ + Esc", "强制退出应用"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⌃ + ⌘ + Power", "强制重启"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⌘ + F5", "开启 / 关闭 VoiceOver"),
        ShortcutItem("macOS", "截图与系统", "进阶", "⌥ + ⌘ + F1/F2", "打开显示器设置（旧款）"),

        // 进阶
        ShortcutItem("macOS", "进阶", "进阶", "⌥ + 点击菜单栏图标", "快速打开更多系统信息"),
        ShortcutItem("macOS", "进阶", "进阶", "⇧ + ⌥ + 音量键", "微调音量"),
        ShortcutItem("macOS", "进阶", "进阶", "⇧ + ⌥ + 亮度键", "微调亮度"),
        ShortcutItem("macOS", "进阶", "进阶", "⌘ + Shift + G", "访达“前往文件夹”"),
        ShortcutItem("macOS", "进阶", "进阶", "⌘ + Option + D", "显示 / 隐藏 Dock"),
        ShortcutItem("macOS", "进阶", "进阶", "⌘ + Ctrl + Q", "快速锁定屏幕"),
        ShortcutItem("macOS", "进阶", "进阶", "Fn + 左/右箭头", "翻页（Home/End）"),
        ShortcutItem("macOS", "进阶", "进阶", "⌘ + Shift + /", "打开应用帮助菜单搜索")
    )
}
