package com.jisuanyusuiji.toolbox

import com.jisuanyusuiji.toolbox.tools.knowledge.FormulaItem
import com.jisuanyusuiji.toolbox.tools.knowledge.FormulaLegend
import org.junit.Assert.assertTrue
import org.junit.Test

/** 公式“符号说明”生成器的单元测试。 */
class FormulaLegendTest {

    @Test
    fun permutationLegend_explainsNandM() {
        val item = FormulaItem("代数", "排列数", "A(n,m) = n! / (n-m)!", "从 n 个不同元素取 m 个排列")
        val legend = FormulaLegend.of(item)
        assertTrue(legend.contains("元素总数"))
        assertTrue(legend.contains("m：取出的个数"))
        assertTrue(legend.contains("阶乘"))
    }

    @Test
    fun combinationLegend_usesCombinationWording() {
        val item = FormulaItem("代数", "组合数", "C(n,m) = n! / [m!(n-m)!]", "从 n 个不同元素取 m 个组合")
        val legend = FormulaLegend.of(item)
        assertTrue(legend.contains("组合数"))
        assertTrue(legend.contains("不区分顺序"))
    }

    @Test
    fun geometryCircle_legendExplainsR() {
        val item = FormulaItem("几何", "圆面积", "S = πr^2", "圆面积")
        val legend = FormulaLegend.of(item)
        assertTrue(legend.contains("r：半径"))
        assertTrue(legend.contains("π"))
    }

    @Test
    fun contextLegend_runsForAutoGeneratedFormulas() {
        // 没有手工说明时，也应能从“几何”语境推出 a、b、c、S 的含义
        val item = FormulaItem("几何", "自定义三角形公式", "R = abc/(4S)", "三角形外接圆半径")
        val legend = FormulaLegend.of(item)
        assertTrue(legend.contains("a"))
        assertTrue(legend.contains("S"))
    }

    @Test
    fun scienceConstant_hasNoForcedLegend() {
        val item = FormulaItem("科学常数", "真空光速", "c = 299792458 m/s", "电磁波在真空中的传播速度")
        assertTrue(FormulaLegend.of(item).isEmpty())
    }
}
